# Generated by Django 6.0 on 2025-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqlorm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
