# Generated by Django 6.0 on 2025-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqlorm_app", "0002_task_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(help_text="The task description", max_length=200),
        ),
    ]
